name: ima_player_prototype
description: ima player prototype
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"
dependencies:
  flutter_bloc: ^7.0.0
  get_it: ^7.2.0
  equatable: ^2.0.0
  animated_text_kit: ^4.2.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true




